version: '3'
services:
  web:
    image: odoo:14  # você pode mudar para a versão do Odoo que desejar
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./my_modules:/mnt/extra-addons
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
volumes:
  odoo-web-data:
  config:
  addons: